title:            Clayton 'at' xDevel
description:      Aqui emcontrará pequenas notas e dicas que passo no meu dia a dia, não existe um período que não faça nada novo.
disqus_shortname: xDevel
reading_time:     true
words_per_minute: 200
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://claytonsilva.github.io

# Owner/author information
owner:
  name:           Clayton Santos da Silva
  avatar:         Perfil.png
  bio:            "Fundador da xDevel Sistemas, apaixonado por novas tecnologias, estou em contínuo aprendizado."
  email:          clayton@xdevel.com.br
  # Social networking links used in footer. Update and remove as you like.
  twitter:        pakoteplastico
  facebook:       clayton.ssilva
  github:         claytonsilva
  stackexchange:  http://pt.stackoverflow.com/users/7088/clayton-silva
  linkedin:       http://www.linkedin.com/pub/clayton-santos-da-silva/51/94b/b6b
  instagram:      
  flickr:         
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +ClaytonSantosdaSilvaxDevel

# Background image to be tiled on all pages
background: bg.png

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-43313456-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: xDevel Sistemas
    url: http://xdevel.com.br
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
